const ROLE_CODES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  DISPATCHER: "DISPATCHER",
  ONSITE_SPECIALIST: "ONSITE_SPECIALIST",
  SALES: "SALES",
  FINANCE_MGMT: "FINANCE_MGMT"
};

const ROLE_LABELS = {
  [ROLE_CODES.SUPER_ADMIN]: "超级管理员",
  [ROLE_CODES.DISPATCHER]: "采购/调度员",
  [ROLE_CODES.ONSITE_SPECIALIST]: "现场/过驳专员",
  [ROLE_CODES.SALES]: "销售经理/销售员",
  [ROLE_CODES.FINANCE_MGMT]: "财务/管理层"
};

const PERMISSION_CODES = {
  MENU_WORKBENCH: "MENU_WORKBENCH",
  MENU_PROCUREMENT: "MENU_PROCUREMENT",
  MENU_SHIP_POSITION: "MENU_SHIP_POSITION",
  MENU_LIGHTERING: "MENU_LIGHTERING",
  MENU_STOCK_IN: "MENU_STOCK_IN",
  MENU_EXPENSE: "MENU_EXPENSE",
  MENU_SALES: "MENU_SALES",
  MENU_FINANCE: "MENU_FINANCE",
  MENU_APPROVAL: "MENU_APPROVAL",
  MENU_AUDIT: "MENU_AUDIT",

  API_WORKBENCH_AGGREGATE: "API_WORKBENCH_AGGREGATE",
  API_PROCUREMENT_LIST: "API_PROCUREMENT_LIST",
  API_PROCUREMENT_UPDATE: "API_PROCUREMENT_UPDATE",
  API_SHIP_POSITION: "API_SHIP_POSITION",
  API_LIGHTERING_CONFIRM: "API_LIGHTERING_CONFIRM",
  API_STOCKIN_CONFIRM: "API_STOCKIN_CONFIRM",
  API_EXPENSE_SAVE: "API_EXPENSE_SAVE",
  API_SALES_CREATE: "API_SALES_CREATE",
  API_WEIGHING_UPLOAD: "API_WEIGHING_UPLOAD",
  API_PAYMENT_CONFIRM: "API_PAYMENT_CONFIRM",
  API_APPROVAL_REVIEW: "API_APPROVAL_REVIEW",
  API_AUDIT_READ: "API_AUDIT_READ",

  FIELD_PROCUREMENT_UNIT_PRICE_VIEW: "FIELD_PROCUREMENT_UNIT_PRICE_VIEW",
  FIELD_PROCUREMENT_TOTAL_AMOUNT_VIEW: "FIELD_PROCUREMENT_TOTAL_AMOUNT_VIEW",
  FIELD_VOYAGE_COST_VIEW: "FIELD_VOYAGE_COST_VIEW",
  FIELD_VOYAGE_PROFIT_VIEW: "FIELD_VOYAGE_PROFIT_VIEW",

  ACTION_PAYMENT_CONFIRM: "ACTION_PAYMENT_CONFIRM",
  ACTION_LOCKED_CHANGE_SUBMIT_APPROVAL: "ACTION_LOCKED_CHANGE_SUBMIT_APPROVAL",
  ACTION_APPROVAL_REVIEW: "ACTION_APPROVAL_REVIEW"
};

const ROLE_PERMISSION_MATRIX = {
  [ROLE_CODES.SUPER_ADMIN]: Object.values(PERMISSION_CODES),
  [ROLE_CODES.DISPATCHER]: [
    PERMISSION_CODES.MENU_WORKBENCH,
    PERMISSION_CODES.MENU_PROCUREMENT,
    PERMISSION_CODES.MENU_SHIP_POSITION,
    PERMISSION_CODES.API_WORKBENCH_AGGREGATE,
    PERMISSION_CODES.API_PROCUREMENT_LIST,
    PERMISSION_CODES.API_PROCUREMENT_UPDATE,
    PERMISSION_CODES.API_SHIP_POSITION,
    PERMISSION_CODES.ACTION_LOCKED_CHANGE_SUBMIT_APPROVAL
  ],
  [ROLE_CODES.ONSITE_SPECIALIST]: [
    PERMISSION_CODES.MENU_WORKBENCH,
    PERMISSION_CODES.MENU_LIGHTERING,
    PERMISSION_CODES.MENU_STOCK_IN,
    PERMISSION_CODES.MENU_EXPENSE,
    PERMISSION_CODES.API_WORKBENCH_AGGREGATE,
    PERMISSION_CODES.API_LIGHTERING_CONFIRM,
    PERMISSION_CODES.API_STOCKIN_CONFIRM,
    PERMISSION_CODES.API_EXPENSE_SAVE,
    PERMISSION_CODES.ACTION_LOCKED_CHANGE_SUBMIT_APPROVAL
  ],
  [ROLE_CODES.SALES]: [
    PERMISSION_CODES.MENU_WORKBENCH,
    PERMISSION_CODES.MENU_SALES,
    PERMISSION_CODES.API_WORKBENCH_AGGREGATE,
    PERMISSION_CODES.API_SALES_CREATE,
    PERMISSION_CODES.API_WEIGHING_UPLOAD
  ],
  [ROLE_CODES.FINANCE_MGMT]: [
    PERMISSION_CODES.MENU_WORKBENCH,
    PERMISSION_CODES.MENU_FINANCE,
    PERMISSION_CODES.MENU_APPROVAL,
    PERMISSION_CODES.MENU_AUDIT,
    PERMISSION_CODES.API_WORKBENCH_AGGREGATE,
    PERMISSION_CODES.API_PAYMENT_CONFIRM,
    PERMISSION_CODES.API_APPROVAL_REVIEW,
    PERMISSION_CODES.API_AUDIT_READ,
    PERMISSION_CODES.FIELD_PROCUREMENT_UNIT_PRICE_VIEW,
    PERMISSION_CODES.FIELD_PROCUREMENT_TOTAL_AMOUNT_VIEW,
    PERMISSION_CODES.FIELD_VOYAGE_COST_VIEW,
    PERMISSION_CODES.FIELD_VOYAGE_PROFIT_VIEW,
    PERMISSION_CODES.ACTION_PAYMENT_CONFIRM,
    PERMISSION_CODES.ACTION_LOCKED_CHANGE_SUBMIT_APPROVAL,
    PERMISSION_CODES.ACTION_APPROVAL_REVIEW
  ]
};

const SENSITIVE_FIELD_KEYS = {
  PROCUREMENT_UNIT_PRICE: "procurement.unit_price",
  PROCUREMENT_TOTAL_AMOUNT: "procurement.total_amount",
  VOYAGE_COST_AMOUNT: "voyage.cost_amount",
  VOYAGE_PROFIT_AMOUNT: "voyage.profit_amount"
};

const FIELD_PERMISSION_MAPPING = {
  [SENSITIVE_FIELD_KEYS.PROCUREMENT_UNIT_PRICE]: PERMISSION_CODES.FIELD_PROCUREMENT_UNIT_PRICE_VIEW,
  [SENSITIVE_FIELD_KEYS.PROCUREMENT_TOTAL_AMOUNT]: PERMISSION_CODES.FIELD_PROCUREMENT_TOTAL_AMOUNT_VIEW,
  [SENSITIVE_FIELD_KEYS.VOYAGE_COST_AMOUNT]: PERMISSION_CODES.FIELD_VOYAGE_COST_VIEW,
  [SENSITIVE_FIELD_KEYS.VOYAGE_PROFIT_AMOUNT]: PERMISSION_CODES.FIELD_VOYAGE_PROFIT_VIEW
};

module.exports = {
  ROLE_CODES,
  ROLE_LABELS,
  PERMISSION_CODES,
  ROLE_PERMISSION_MATRIX,
  SENSITIVE_FIELD_KEYS,
  FIELD_PERMISSION_MAPPING
};
